config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match 'pubsubhubbub/post', to: 'youtube_webhook_verifications#create', via: [:get, :post]

  namespace :control_panel, path: 'controlpanel' do
    resources :channels, only: :show do
      resource :suspension, only: :create, module: :channels
    end
    resources :videos, only: [:show, :edit, :update]
  end

  namespace :sites_setup, path: 'sites/:site_id/welcome' do
    resource :details, only: [:edit, :update], path: 'your-site'
    resource :users, only: [:new, :create], path: 'account'
  end

  resources :sites, only: [:create, :show]
  resources :channels, only: [:show, :edit, :update]
  resources :notification_subscriptions, only: [:create]
  delete :notification_subscriptions, to: 'notification_subscriptions#destroy'

  root 'static#home_page'
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :site
  has_many :videos
  has_many :notification_subscriptions, as: :subscribeable
  validates :site, presence: true
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel

  def show
  end

  def edit
  end

  def update
    if @channel.update!(channel_params)
      flash['notice'] = "#{@channel.name} has been updated successfully."
      redirect_to channel_path(@channel)
    else
      render :edit
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name, :description)
  end

  def set_channel
    @channel = Channel.find(params[:id])
  end
end

app/controllers/control_panel/channels/suspensions_controller.rb
class ControlPanel::Channels::SuspensionsController < ControlPanel::BaseController
  before_action :set_channel

  def create
    @channel.update(suspended_at: Time.zone.now)
    flash['notice'] = "#{@channel.name} has been suspended."
    redirect_to control_panel_channel_path(@channel)
  end

  private

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end
end

app/controllers/control_panel/channels_controller.rb
class ControlPanel::ChannelsController < ControlPanel::BaseController
  before_action :set_channel

  def show
    authorize @channel
    @videos = @channel.videos.order("updated_at desc")
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end
end

app/views/channels/edit.html.erb
<div class="flex flex-col">
  <%= form_with model: @channel do |f| %>
    <div>
      <%= f.text_field :name, class: 'border rounded-md' %>
    </div>
    <div>
      <%= f.text_area :description, class: 'border rounded-md' %>
    </div>
    <div>
      <%= f.submit 'Update Channel', class: 'rounded-lg px-4 md:px-5 xl:px-4 py-3 md:py-4 xl:py-3 bg-teal-500 hover:bg-teal-600 md:text-lg xl:text-base text-white font-semibold leading-tight shadow-md' %>
    </div>
  <% end %>
</div>

app/views/channels/show.html.erb
<div class="container mx-auto">
  <h1 class="text-lg font-bold">
    <%= @channel.name %>
  </h1>
  <h4>
    Organisation: <%= @channel.site.organisation.name %>
  </h4>


  <div class="m-12">
    <%= turbo_stream_from [current_user, @channel], :notification_subscriptions %>
    <div id="notification_subscriptions"></div>
  </div>

  <%= link_to 'Edit Channel', edit_channel_path(@channel), class: 'text-blue-500' %>
  <% if NotificationSubscription.user_has_active_subscription_for?(user: current_user, subscribeable: @channel) %>
    <div>
      You're Subscribed 🤩
      <%= button_to "Unsubscribe", notification_subscriptions_path(subscribeable_id: @channel.id, subscribeable_type: @channel.class.name), method: :delete, class: 'btn' %>
    </div>
  <% else %>
    <%= button_to "Subscribe", notification_subscriptions_path(subscribeable_id: @channel.id, subscribeable_type: @channel.class.name), method: :post, class: 'btn' %>
  <% end %>

  <% if @channel.videos.empty? %>
    <div class="text-lg font-bold">
      There are no videos for this channel (yet!).
    </div>
  <% else %>
    <% @channel.videos.each do |video| %>
      <div>
        <img src="<%= video.thumbnail_url %>" style="max-width: 250px">
        <br>
        <div class="text-lg font-bold">
          <%= video.title %>
        </div>
        <p>
          <%= video.description %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>