config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match 'pubsubhubbub/post', to: 'youtube_webhook_verifications#create', via: [:get, :post]

  namespace :control_panel, path: 'controlpanel' do
    resources :channels, only: :show do
      resource :suspension, only: :create, module: :channels
    end
    resources :videos, only: [:show, :edit, :update]
  end

  namespace :sites_setup, path: 'sites/:site_id/welcome' do
    resource :details, only: [:edit, :update], path: 'your-site'
    resource :users, only: [:new, :create], path: 'account'
  end

  resources :sites, only: [:create, :show]
  resources :channels, only: [:show, :edit, :update]
  resources :notification_subscriptions, only: [:create]
  delete :notification_subscriptions, to: 'notification_subscriptions#destroy'

  root 'static#home_page'
end

app/controllers/sites_setup/base_controller.rb
# frozen_string_literal: true

class SitesSetup::BaseController < ApplicationController
  before_action :set_site

  private

  def set_site
    @site = Site.find(params[:site_id])
  end
end

app/controllers/sites_setup/details_controller.rb
# frozen_string_literal: true

class SitesSetup::DetailsController < SitesSetup::BaseController
  def edit
    @channel = Channel.new(site: @site)
  end

  def update
    @channel = Channel.new(site: @site)
    @channel.assign_attributes(channel_params)
    if @channel.save
      PopulateChannelVideosJob.set(wait: 30.seconds).perform_later(channel: @channel)
      redirect_to new_sites_setup_users_path(@site)
    else
      render :edit
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:youtube_channel_id)
  end
end

app/controllers/sites_setup/users_controller.rb
# frozen_string_literal: true

class SitesSetup::UsersController < SitesSetup::BaseController
  before_action :set_site

  def new
  end

  def create
    @user = User.new(user_params)
    @user.organisation = @site.organisation
    if @user.save
      flash[:notice] = "Your user account has been created!"
      sign_in @user
      redirect_to site_path(@site)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def set_site
    @site = Site.find(params[:site_id])
  end
end

app/views/sites_setup/details/edit.html.erb
<div class="mt-12">
  <div class="max-w-lg p-3 mx-auto bg-white shadow sm:rounded-lg">
    <p>
      This is where the form will go to update the Site model!
    </p>

    <%= form_with model: @channel, url: sites_setup_details_path, method: :patch, data: { turbo: false, remote: false } do |f| %>
      <div class="grid grid-cols-3 gap-6 mb-8">
        <div class="col-span-3">
          <label for="company_website" class="block text-sm font-medium text-gray-700">
            What's the ID of your YouTube Channel?
          </label>
          <div class="mt-1 flex rounded-md shadow-sm">
            <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
              http://www.youtube.com/channel/
            </span>
            <%= f.text_field :youtube_channel_id,
                             class: 'focus:ring-indigo-500 focus:border-indigo-500 '\
                                    'flex-1 block w-full rounded-none rounded-r-md '\
                                    'sm:text-sm border-gray-300' %>
          </div>
        </div>
      </div>
      <div class="text-center mx-auto mb-8">
        <%= f.submit 'Submit', class: 'btn' %>
      </div>
    <% end %>
    <%= link_to 'Skip to Step 3', new_sites_setup_users_path %>
  </div>
</div>