config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match 'pubsubhubbub/post', to: 'youtube_webhook_verifications#create', via: [:get, :post]

  namespace :control_panel, path: 'controlpanel' do
    resources :channels, only: :show do
      resource :suspension, only: :create, module: :channels
    end
    resources :videos, only: [:show, :edit, :update]
  end

  namespace :sites_setup, path: 'sites/:site_id/welcome' do
    resource :details, only: [:edit, :update], path: 'your-site'
    resource :users, only: [:new, :create], path: 'account'
  end

  resources :sites, only: [:create, :show]
  resources :channels, only: [:show, :edit, :update]
  resources :notification_subscriptions, only: [:create]
  delete :notification_subscriptions, to: 'notification_subscriptions#destroy'

  root 'static#home_page'
end

app/models/video.rb
class Video < ApplicationRecord
  has_paper_trail

  belongs_to :channel
end

app/controllers/control_panel/base_controller.rb
class ControlPanel::BaseController < ApplicationController
  before_action :authenticate_user!

  def authorize(record, query = nil)
    super([:control_panel, record], query)
  end
end

app/controllers/control_panel/channels/suspensions_controller.rb
class ControlPanel::Channels::SuspensionsController < ControlPanel::BaseController
  before_action :set_channel

  def create
    @channel.update(suspended_at: Time.zone.now)
    flash['notice'] = "#{@channel.name} has been suspended."
    redirect_to control_panel_channel_path(@channel)
  end

  private

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end
end

app/controllers/control_panel/channels_controller.rb
class ControlPanel::ChannelsController < ControlPanel::BaseController
  before_action :set_channel

  def show
    authorize @channel
    @videos = @channel.videos.order("updated_at desc")
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end
end

app/controllers/control_panel/videos_controller.rb
class ControlPanel::VideosController < ControlPanel::BaseController
  before_action :set_video

  def show
  end

  def edit
  end

  def update
    if @video.update(video_params)
      flash[:notice] = "Updated Video Successfully"
      redirect_to control_panel_channel_path(@video.channel)
    else
      render :edit
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :description)
  end
end

app/views/control_panel/videos/_form.html.erb
<turbo-frame id="<%= dom_id(@video) %>">
  <div class="flex flex-col">
    <%= form_with model: [:control_panel, @video] do |f| %>
      <div>
        <%= f.text_field :title, class: 'border rounded-md' %>
      </div>
      <div>
        <%= f.text_area :description, class: 'border rounded-md' %>
      </div>
      <div>
        <%= f.submit 'Update Video', class: 'btn' %>
      </div>
      <%= link_to 'Cancel', control_panel_channel_path(@video.channel) %>
    <% end %>
  </div>
</turbo-frame>

app/views/control_panel/videos/_video.html.erb
<turbo-frame id="<%= dom_id(video) %>">
  <div>
    <img src="<%= video.thumbnail_url %>" style="max-width: 250px">
    <br>
    <div class="text-lg font-bold">
      <%= link_to video.title, control_panel_video_path(video), target: '_top' %>
    </div>
    <p>
      <%= video.description %>
    </p>
  </div>
  <div>
    <%= link_to 'Edit', edit_control_panel_video_path(video), class: 'btn' %>
  </div>
</turbo-frame>

app/views/control_panel/videos/edit.html.erb
Editing Video #<%= @video.id %>

<%= render 'form' %>

app/views/control_panel/videos/show.html.erb
Showing Video #<%= @video.id %>
<div>
  Versions:
  <% @video.versions.each do |version| %>
    <div>
      <%= version.object %><%= link_to 'Restore', '#', class: 'btn' %>
    </div>
  <% end %>
</div>